// <auto-generated />
using System;
using HWMS.Infrastructure.Contexts.OracleContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace HWMS.Infrastructure.Migrations.OracleMigration
{
    [DbContext(typeof(O_HWMSContext))]
    [Migration("20210718151527_UpdateNavigationOfLength")]
    partial class UpdateNavigationOfLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HWMS.DoMain.Models.Access.NavigationMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ParentMenuId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Visible")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.ToTable("NavigationMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
